import "CharacterSheet.idl";


namespace BlankApp1BindingTest
{
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();
        Int32 MyProperty;
        CharacterSheet ViewModel{ get; };
    }
}
